name: container build-and-push process
description: "Construye la container image"
author: "DevOps Team"

runs:
  using: "composite"
  steps:
    - name: container-build-push
      shell: bash
      run: |
        set -euo pipefail
        GREEN='\033[0;32m'
        NC='\033[0m' # No Color

        echo -ne "🚀 ${GREEN}[INFO]: CONSTRUYENDO LA IMAGEN${NC}\n"

        SCRIPTS_PATH=".ci-toolkit/.github/scripts"
        export SCRIPTS_PATH
        echo "SCRIPTS_PATH=${SCRIPTS_PATH}" >> $GITHUB_ENV

        EXECUTE_SCRIPT="${SCRIPTS_PATH}/shell/container/build-and-push.sh"
        chmod +x ${EXECUTE_SCRIPT}
        ${EXECUTE_SCRIPT}
