---
name: GitOps Tag and Release Creator
description: Crea un tag de release y una release en GitHub con el mismo nombre, validando que el tag siga el patrón semver y que no exista una release con ese tag previamente creada
inputs:
  release_version:
    description: "La versión de release a validar (debe seguir el patrón semver, ej: v1.2.3)"
    required: true
  github_token:
    description: "Token de GitHub con permisos para crear tags y releases en el repositorio"
    required: true
  environment:
    description: "El entorno para el cual se está creando la release (ej: staging, production)"
    required: false
    default: "dev"
runs:
  using: "composite"
  steps:
    - name: Set shared paths
      shell: bash
      run: |
        SCRIPTS_PATH=".ci-toolkit/.github/scripts"
        SCRIPT="${SCRIPTS_PATH}/shell/gitops/tag-release-creator/tag-and-release-creator.sh"
        chmod +x "${SCRIPT}"
        echo "SCRIPTS_PATH=${SCRIPTS_PATH}" >> $GITHUB_ENV
        echo "TAG_AND_RELEASE_CREATOR_SCRIPT=${SCRIPT}" >> $GITHUB_ENV

    - name: Create Tag and Release
      shell: bash
      env:
        INPUT_RELEASE_VERSION: ${{ inputs.release_version }}
        INPUT_ENVIRONMENT: ${{ inputs.environment }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        set -euo pipefail
        "${TAG_AND_RELEASE_CREATOR_SCRIPT}"
