---
name: CI/CD Dispatcher

on:
  workflow_call:
    outputs:
      container_image_name_ghcr:
        description: "the name of the container in GHCR"
        value: ${{ jobs.container-build-and-push.outputs.container_image_name_ghcr }}
      container_image_digest_ghcr:
        description: "The digest of the container image in GHCR"
        value: ${{ jobs.container-build-and-push.outputs.container_image_digest_ghcr }}
      client_repo_sha:
        description: "The SHA of the commit in the client repository (called the shared library)"
        value: ${{ jobs.resolve-ci-context.outputs.client_repo_sha }}
    inputs:
      target_action:
        required: true
        type: string

jobs:
  resolve-ci-context:
    name: "ValidateContext(Event: ${{ github.event_name }})"
    runs-on: ubuntu-slim
    outputs:
      should_run: ${{ steps.ctx.outputs.should_run }}
      is_pr: ${{ steps.ctx.outputs.is_pr }}
      is_push: ${{ steps.ctx.outputs.is_push }}
      is_dispatch: ${{ steps.ctx.outputs.is_dispatch }}
      is_hotfix_branch: ${{ steps.ctx.outputs.is_hotfix_branch }}
      release_version: ${{ steps.ctx.outputs.release_version }}
      release_version_semver: ${{ steps.ctx.outputs.release_version_semver }}
      active_branch: ${{ steps.ctx.outputs.active_branch }}
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Checkout monorepo(workflows and actions)
        uses: actions/checkout@v5
        with:
          repository: niels-baltodano/ghp-shared-workflows
          ref: main
          path: .ci-toolkit
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          persist-credentials: true

      - name: Resolve CI/CD context
        id: ctx
        uses: ./.ci-toolkit/.github/actions/resolve-ci-context
        with:
          input_target_action: ${{ inputs.target_action }}

  container-build-and-push:
    needs: [resolve-ci-context]
    if: >-
      needs.resolve-ci-context.outputs.should_run == 'true' &&
      needs.resolve-ci-context.outputs.is_container == 'true' &&
      needs.resolve-ci-context.is_dispatch == 'true'
    uses: ./.github/workflows/container-build-push.yml
    with:
      release_version: ${{ needs.resolve-ci-context.outputs.release_version }}
      #project_language: ${{ needs.container-pre-build.outputs.project_language }}
      security_allow_push_to_ghcr: ${{ vars.SECURITY_ALLOW_PUSH_TO_GHCR || 'false' }}
